Repository etcd-io/jetcd, pull requests merged in 2024-08, with the labels that each got.

#1371 [chore] Update etcd container version to 3.5.14.
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
  jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/Etcd.java
Labels: size/S

#1386 build(deps): bump errorprone from 2.28.0 to 2.29.2
  gradle/libs.versions.toml
Labels: size/XS, approved

#1390 jetcd-launcher: allow starting Etcd Container via non-root user on Linux
  jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/Etcd.java
  jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdClusterImpl.java
  jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdContainer.java
  jetcd-test/src/main/java/io/etcd/jetcd/test/EtcdClusterExtension.java
Labels: approved, size/M

#1394 chore: switch to quay as gcr is deprecated
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
  jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/Etcd.java
  jetcd-launcher/src/test/resources/log4j2.xml
Labels: size/S, approved
